site_name: E-Cell project
pages:
- Top: index.md
- About: about.md
- Projects:
    - 'Projects': 'projects/projects.md'
    - 'Models': 'projects/models.md'
- Publications: publications.md
- Community:
    - 'Community': 'community/community.md'
theme: readthedocs
