site_name: E-Cell project
pages:
- Top: index.md
- About: about.md
- Projects:
    - 'Projects': 'projects/projects.md'
    - 'Downloads': 'projects/downloads.md'
    - 'Models': 'projects/models.md'
- Publications: publications.md
- Community: community.md
theme: bootstrap